name: popgame
description: A new Flutter project.

publish_to: "none"

version: 0.0.1+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  auto_size_text: ^3.0.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.9
  get: ^4.6.6
  just_audio: ^0.9.35
  lottie: ^2.7.0

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: BoldFont
      fonts:
        - asset: assets/fonts/Sans Condensed BOLD.ttf

 

  assets:
    - assets/
    - assets/alphabet/
    - assets/balloons/
    - assets/fonts/
    - assets/images/
    - assets/lottie/
    - assets/music/
    - assets/voices/
